name: GCP Inventory Workflow

on:
  workflow_dispatch:

jobs:
  gcp-inventory:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Decode GCP Key from GitHub Secret
    - name: Decode GCP Key
      run: |
        echo "${{ secrets.GCP_KEY_BASE64 }}" | base64 -d > gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV

    # 4. Install Python Dependencies
    - name: Install Python Dependencies
      run: |
        pip install --upgrade pip
        pip install google-cloud-compute google-cloud-storage google-cloud-bigquery google-cloud-monitoring
        pip install google-auth google-auth-oauthlib google-auth-httplib2 grpcio protobuf Jinja2 google-api-python-client

    # 5. Run GCP VM Inventory Script
    - name: Run GCP VM Inventory Script
      run: python VirtualMachine/VirtualMachine.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
